In [1]:
import numpy as np
import pandas as pd
import fuzzywuzzy
from fuzzywuzzy import process
import charset_normalizer

d:\jupyter_notebook\Lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [ ]:
waveMusic_Df= pd.read_csv('../data/DataWave_Music_Sprint_Dataset - DataWave_Music_Sprint_Dataset.csv')
waveMusic_Df.head()

,user_id,country,age,gender,subscription_type,avg_listening_hours_per_week,total_songs_played,skip_rate,satisfaction_score,churned,monthly_fee,join_date
0,U1403,Nepal,23,F,Premum,11.5,510,5%,2.0,0,7.99,03/21/2024
1,U1165,Nepal,63,male,Student,11.3,526,5%,3.0,0,0,08/10/2023
2,U1474,USA,45,F,Premum,2.0,476,30%,3.0,0,7.99,04/05/2022
3,U1478,Nigeria,16,F,Family,12.1,529,20%,5.0,yes,12.99,12/16/2023
4,U1609,Ghana,29,M,Free,6.4,477,0.2,3.0,0,7.99,03/28/2022

In [3]:
waveMusic_Df.isna().sum()

user_id                         10
country                          0
age                              0
gender                          79
subscription_type                0
avg_listening_hours_per_week     0
total_songs_played               0
skip_rate                        0
satisfaction_score              44
churned                          0
monthly_fee                     33
join_date                        0
dtype: int64

In [4]:
waveMusic_Df["user_id"].duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
700    False
701    False
702    False
703    False
704    False
Name: user_id, Length: 705, dtype: bool

In [5]:
missing= waveMusic_Df.isna().sum()
percentMissing= (waveMusic_Df.isna().sum()/len(waveMusic_Df))*100
missing_data = pd.DataFrame({'Missing data':missing, 'percentage %':percentMissing})
print(missing_data)

                              Missing data  percentage %
user_id                                 10      1.418440
country                                  0      0.000000
age                                      0      0.000000
gender                                  79     11.205674
subscription_type                        0      0.000000
avg_listening_hours_per_week             0      0.000000
total_songs_played                       0      0.000000
skip_rate                                0      0.000000
satisfaction_score                      44      6.241135
churned                                  0      0.000000
monthly_fee                             33      4.680851
join_date                                0      0.000000

In [6]:
waveMusic_Df = waveMusic_Df.dropna(subset='user_id')

In [7]:
waveMusic_Df[waveMusic_Df['gender'].isna()]

,user_id,country,age,gender,subscription_type,avg_listening_hours_per_week,total_songs_played,skip_rate,satisfaction_score,churned,monthly_fee,join_date
6,U1262,Nigeria,59,NaN,Free,7.4,502,25%,1.0,1,9.99,27/06/2022
19,U1107,South Africa,33,NaN,Premum,14.6,512,30%,2.0,0,0,02/03/2023
20,U1568,Nigeria,33,NaN,Premum,11.0,522,20%,3.0,1,7.99,18/04/2024
46,U1511,Nigeria,39,NaN,Free,10.7,531,25%,2.0,1,9.99,19/12/2023
48,U1281,Nigeria,25,NaN,Family,4.5,483,10%,3.0,0,NaN,01/09/2023
...,...,...,...,...,...,...,...,...,...,...,...,...
670,U1330,IND,36,NaN,Family,7.8,503,5%,3.0,0,0,25/11/2022
675,U1549,Brazil,41,NaN,Studnt,17.7,498,ten,3.0,0,12.99,24/11/2022
677,U1137,United Kingdom,59,NaN,Fam,7.5,538,10%,2.0,1,7.99,04/21/2024
688,U1229,UK,34,NaN,Free,19.4,508,25%,1.0,0,NaN,04/08/2022
701,U1143,IND,14,NaN,Premium,10.2,518,10%,4.0,0,9.99,03/03/2024

In [8]:
waveMusic_Df.describe

<bound method NDFrame.describe of     user_id         country  age  gender subscription_type  \
0     U1403           Nepal   23       F            Premum
1     U1165           Nepal   63    male           Student
2     U1474             USA   45       F            Premum
3     U1478         Nigeria   16       F            Family
4     U1609           Ghana   29       M              Free
..      ...             ...  ...     ...               ...
700   U1584  United Kingdom   30    Male           Student
701   U1143             IND   14     NaN           Premium
702   U1524             IND   55    male           Premium
703   U1046           Kenya   48  Female              Free
704   U1022           Nepal   13  Female               Fam

     avg_listening_hours_per_week  total_songs_played skip_rate  \
0                            11.5                 510        5%
1                            11.3                 526        5%
2                             2.0                 476       30%
3                            12.1                 529       20%
4                             6.4                 477       0.2
..                            ...                 ...       ...
700                          19.2                 458       30%
701                          10.2                 518       10%
702                           5.5                 517        5%
703                           1.0                 562       30%
704                           7.8                 498       30%

     satisfaction_score churned monthly_fee   join_date
0                   2.0       0        7.99  03/21/2024
1                   3.0       0           0  08/10/2023
2                   3.0       0        7.99  04/05/2022
3                   5.0     yes       12.99  12/16/2023
4                   3.0       0        7.99  03/28/2022
..                  ...     ...         ...         ...
700                 4.0      no        7.99  07/21/2023
701                 4.0       0        9.99  03/03/2024
702                 4.0       0           0  25/10/2023
703                 5.0      no           0  02/06/2022
704                 5.0       0        7.99  05/12/2022

[695 rows x 12 columns]>

In [9]:
waveMusic_Df.head()

,user_id,country,age,gender,subscription_type,avg_listening_hours_per_week,total_songs_played,skip_rate,satisfaction_score,churned,monthly_fee,join_date
0,U1403,Nepal,23,F,Premum,11.5,510,5%,2.0,0,7.99,03/21/2024
1,U1165,Nepal,63,male,Student,11.3,526,5%,3.0,0,0,08/10/2023
2,U1474,USA,45,F,Premum,2.0,476,30%,3.0,0,7.99,04/05/2022
3,U1478,Nigeria,16,F,Family,12.1,529,20%,5.0,yes,12.99,12/16/2023
4,U1609,Ghana,29,M,Free,6.4,477,0.2,3.0,0,7.99,03/28/2022

In [10]:
waveMusic_country =waveMusic_Df['country'].unique()
waveMusic_country.sort()
waveMusic_country

array(['Brazil', 'Ghana', 'IND', 'India', 'Kenya', 'Nepal', 'Nigeria',
       'South Africa', 'U.K.', 'UK', 'USA', 'United Kingdom'],
      dtype=object)

In [11]:
waveMusic_Df.isna().sum()

user_id                          0
country                          0
age                              0
gender                          79
subscription_type                0
avg_listening_hours_per_week     0
total_songs_played               0
skip_rate                        0
satisfaction_score              44
churned                          0
monthly_fee                     33
join_date                        0
dtype: int64

In [ ]:
waveMusic_Df['country']= waveMusic_Df['country'].str.lower().str.strip()

In [13]:
waveMusic_Df['country'] = waveMusic_Df['country'].replace('IND', 'India')

In [14]:
waveMusic_Df.head()

,user_id,country,age,gender,subscription_type,avg_listening_hours_per_week,total_songs_played,skip_rate,satisfaction_score,churned,monthly_fee,join_date,Country
0,U1403,Nepal,23,F,Premum,11.5,510,5%,2.0,0,7.99,03/21/2024,nepal
1,U1165,Nepal,63,male,Student,11.3,526,5%,3.0,0,0,08/10/2023,nepal
2,U1474,USA,45,F,Premum,2.0,476,30%,3.0,0,7.99,04/05/2022,usa
3,U1478,Nigeria,16,F,Family,12.1,529,20%,5.0,yes,12.99,12/16/2023,nigeria
4,U1609,Ghana,29,M,Free,6.4,477,0.2,3.0,0,7.99,03/28/2022,ghana

In [15]:
waveMusic_Df['country'] = waveMusic_Df['country'].replace(('UK','U.K.'), 'United Kingdom')

In [16]:
waveMusic_gender =waveMusic_Df['gender'].unique()
waveMusic_gender

array(['F', 'male', 'M', 'female', nan, 'Male', 'Female', 'Other'],
      dtype=object)

In [17]:
waveMusic_Df

,user_id,country,age,gender,subscription_type,avg_listening_hours_per_week,total_songs_played,skip_rate,satisfaction_score,churned,monthly_fee,join_date,Country
0,U1403,Nepal,23,F,Premum,11.5,510,5%,2.0,0,7.99,03/21/2024,nepal
1,U1165,Nepal,63,male,Student,11.3,526,5%,3.0,0,0,08/10/2023,nepal
2,U1474,USA,45,F,Premum,2.0,476,30%,3.0,0,7.99,04/05/2022,usa
3,U1478,Nigeria,16,F,Family,12.1,529,20%,5.0,yes,12.99,12/16/2023,nigeria
4,U1609,Ghana,29,M,Free,6.4,477,0.2,3.0,0,7.99,03/28/2022,ghana
...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,U1584,United Kingdom,30,Male,Student,19.2,458,30%,4.0,no,7.99,07/21/2023,united kingdom
701,U1143,India,14,NaN,Premium,10.2,518,10%,4.0,0,9.99,03/03/2024,ind
702,U1524,India,55,male,Premium,5.5,517,5%,4.0,0,0,25/10/2023,ind
703,U1046,Kenya,48,Female,Free,1.0,562,30%,5.0,no,0,02/06/2022,kenya
704,U1022,Nepal,13,Female,Fam,7.8,498,30%,5.0,0,7.99,05/12/2022,nepal

In [18]:
waveMusic_Df['gender'] = waveMusic_Df['gender'].replace(('male', 'M'),'Male')
waveMusic_Df['gender'] = waveMusic_Df['gender'].replace(('female', 'F'),'Female')

In [22]:
waveMusic_sub = waveMusic_Df['subscription_type'].unique()
print(waveMusic_sub)

['Premium' 'Student' 'Family' 'Free']

In [20]:
waveMusic_Df['subscription_type'] = waveMusic_Df['subscription_type'].replace({
    'Premum': 'Premium',
    'Studnt': 'Student',
    'Fam': 'Family'
})

In [24]:
waveMusic_Df['subscription_type'].head

<bound method NDFrame.head of 0      Premium
1      Student
2      Premium
3       Family
4         Free
        ...
700    Student
701    Premium
702    Premium
703       Free
704     Family
Name: subscription_type, Length: 695, dtype: object>

In [25]:
waveMusic_Df.head()

,user_id,country,age,gender,subscription_type,avg_listening_hours_per_week,total_songs_played,skip_rate,satisfaction_score,churned,monthly_fee,join_date,Country
0,U1403,Nepal,23,Female,Premium,11.5,510,5%,2.0,0,7.99,03/21/2024,nepal
1,U1165,Nepal,63,Male,Student,11.3,526,5%,3.0,0,0,08/10/2023,nepal
2,U1474,USA,45,Female,Premium,2.0,476,30%,3.0,0,7.99,04/05/2022,usa
3,U1478,Nigeria,16,Female,Family,12.1,529,20%,5.0,yes,12.99,12/16/2023,nigeria
4,U1609,Ghana,29,Male,Free,6.4,477,0.2,3.0,0,7.99,03/28/2022,ghana

In [30]:
waveMusic_churend= waveMusic_Df['churned'].unique()
waveMusic_churend

array(['0', 'yes', '1', 'no'], dtype=object)

In [32]:
waveMusic_Df['churned']= waveMusic_Df['churned'].replace({
  '1':'yes',
  '0':'no'  
})

In [37]:
waveMusic_Df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 695 entries, 0 to 704
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   user_id                       695 non-null    object
 1   country                       695 non-null    object
 2   age                           695 non-null    int64
 3   gender                        616 non-null    object
 4   subscription_type             695 non-null    object
 5   avg_listening_hours_per_week  695 non-null    float64
 6   total_songs_played            695 non-null    int64
 7   skip_rate                     695 non-null    object
 8   satisfaction_score            651 non-null    float64
 9   churned                       695 non-null    object
 10  monthly_fee                   662 non-null    object
 11  join_date                     695 non-null    object
 12  Country                       695 non-null    object
dtypes: float64(2), int64(2), object(9)
memory usage: 76.0+ KB